# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cxa < Formula
  desc "Fast, beautiful CLI to manage multiple Codex CLI accounts"
  homepage "https://github.com/delhombre/cxa"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.0/cxa_0.1.0_darwin_amd64.tar.gz"
      sha256 "9097a003cad128aa0865b3c86e45f99b47d2e66992eb7379e2123e9d698b4033"

      def install
        bin.install "cxa"
      end
    end
    on_arm do
      url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.0/cxa_0.1.0_darwin_arm64.tar.gz"
      sha256 "9b3c48c6b913dc505a7f98c480e5a338985566fc3a65b4ec747eb958b4b58910"

      def install
        bin.install "cxa"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.0/cxa_0.1.0_linux_amd64.tar.gz"
        sha256 "52005db161c8df49c5f840c22c3ca4606f71e6516a13b7a00686f2fa416df41f"

        def install
          bin.install "cxa"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.0/cxa_0.1.0_linux_arm64.tar.gz"
        sha256 "3b3350068109aa62200e780656550f020512b68873065db91ad0005c31bfdf76"

        def install
          bin.install "cxa"
        end
      end
    end
  end

  test do
    system "#{bin}/cxa", "version"
  end
end
