# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cxa < Formula
  desc "Fast, beautiful CLI to manage multiple Codex CLI accounts"
  homepage "https://github.com/delhombre/codex-account-switcher"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.1/cxa_0.1.1_darwin_amd64.tar.gz"
      sha256 "3973a50a582201d0a867491aed76495463e2cb426691de6255e4702066b13b0c"

      def install
        bin.install "cxa"
      end
    end
    on_arm do
      url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.1/cxa_0.1.1_darwin_arm64.tar.gz"
      sha256 "af7161bbb52db64f70593474fd3613348b5bb8de7449b5a65a22751d3cb7f601"

      def install
        bin.install "cxa"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.1/cxa_0.1.1_linux_amd64.tar.gz"
        sha256 "1a2422de67a0a73d0260674b97e7563047cce274801c0a958ac7289c15d78c45"

        def install
          bin.install "cxa"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/delhombre/codex-account-switcher/releases/download/v0.1.1/cxa_0.1.1_linux_arm64.tar.gz"
        sha256 "81e556e17b8e54292ffdb69c8ebaf8392a08c41bd489a329474100342071f2cf"

        def install
          bin.install "cxa"
        end
      end
    end
  end

  test do
    system "#{bin}/cxa", "version"
  end
end
